dist: precise
language: cpp

compiler:
    - clang
    - gcc

install:
    - curl https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr

script:
    - mkdir build
    - cd build
    - cmake .. && make
    - ./checkers_test
